schemes:
  dark: &dark
    primary:
      foreground: "#e0def4"
      background: "#232136"
      dim_foreground: "#908caa"
      bright_foreground: "#e0def4"

    cursor:
      text: "#e0def4"
      cursor: "#56526e"

    vi_mode_cursor:
      text: "#e0def4"
      cursor: "#56526e"

    search:
      matches:
        foreground: "#908caa"
        background: "#393552"
      focused_match:
        foreground: "#232136"
        background: "#ea9a97"

    hints:
      start:
        foreground: "#908caa"
        background: "#2a273f"
      end:
        foreground: "#6e6a86"
        background: "#2a273f"

    line_indicator:
      foreground: "None"
      background: "None"

    footer_bar:
      foreground: "#e0def4"
      background: "#2a273f"

    selection:
      text: "#e0def4"
      background: "#44415a"

    normal:
      black: "#393552"
      red: "#eb6f92"
      green: "#3e8fb0"
      yellow: "#f6c177"
      blue: "#9ccfd8"
      magenta: "#c4a7e7"
      cyan: "#ea9a97"
      white: "#e0def4"

    bright:
      black: "#6e6a86"
      red: "#eb6f92"
      green: "#3e8fb0"
      yellow: "#f6c177"
      blue: "#9ccfd8"
      magenta: "#c4a7e7"
      cyan: "#ea9a97"
      white: "#e0def4"

    dim:
      black: "#6e6a86"
      red: "#eb6f92"
      green: "#3e8fb0"
      yellow: "#f6c177"
      blue: "#9ccfd8"
      magenta: "#c4a7e7"
      cyan: "#ea9a97"
      white: "#e0def4"

  light: &light
    primary:
      foreground: "#575279"
      background: "#faf4ed"
      dim_foreground: "#797593"
      bright_foreground: "#575279"

    cursor:
      text: "#575279"
      cursor: "#cecacd"

    vi_mode_cursor:
      text: "#575279"
      cursor: "#cecacd"

    search:
      matches:
        foreground: "#797593"
        background: "#f2e9e1"
      focused_match:
        foreground: "#faf4ed"
        background: "#d7827e"

    hints:
      start:
        foreground: "#797593"
        background: "#fffaf3"
      end:
        foreground: "#9893a5"
        background: "#fffaf3"


    line_indicator:
      foreground: "None"
      background: "None"

    footer_bar:
      foreground: "#575279"
      background: "#fffaf3"

    selection:
      text: "#575279"
      background: "#dfdad9"

    normal:
      black: "#f2e9e1"
      red: "#b4637a"
      green: "#286983"
      yellow: "#ea9d34"
      blue: "#56949f"
      magenta: "#907aa9"
      cyan: "#d7827e"
      white: "#575279"

    bright:
      black: "#9893a5"
      red: "#b4637a"
      green: "#286983"
      yellow: "#ea9d34"
      blue: "#56949f"
      magenta: "#907aa9"
      cyan: "#d7827e"
      white: "#575279"

    dim:
      black: "#9893a5"
      red: "#b4637a"
      green: "#286983"
      yellow: "#ea9d34"
      blue: "#56949f"
      magenta: "#907aa9"
      cyan: "#d7827e"
      white: "#575279"

colors: *dark
