# https://github.com/nik27/night-owl-alacritty-theme/blob/main/night-owl.yml

colors:
  primary:
    background: "#011627"
    foreground: "#d6deeb"

  # Cursor colors
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Vi mode cursor colors
  vi_mode_cursor:
    text: CellBackground
    cursor: "#22da6e"

  # Selection colors
  selection:
    text: "#ffffff"
    background: "#0d486e"

  # Search colors
  search:
    matches:
      foreground: "#000000"
      background: "#22da6e"

      focused_match:
        foreground: "#ffffff"
        background: "#22da6e"

    footer_bar:
      foreground: "#ffffff"
      background: "#1d3b53"

  # Normal colors
  normal:
    black: "#011627"
    red: "#EF5350"
    green: "#22da6e"
    yellow: "#c5e478"
    blue: "#82AAFF"
    magenta: "#C792EA"
    cyan: "#21c7a8"
    white: "#ffffff"

  # Bright colors
  bright:
    black: "#575656"
    red: "#EF5350"
    green: "#22da6e"
    yellow: "#ffeb95"
    blue: "#82AAFF"
    magenta: "#C792EA"
    cyan: "#7fdbca"
    white: "#ffffff"
