# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$cmd_duration\
$dart\
$lua\
$nodejs\
$ruby\
$rust\
$line_break\
$character"""

[character]
success_symbol = "[[â™¥](green) â¯](green)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[cmd_duration]
format = "[ï€— $duration ]($style)"
style = "bold" #white

[directory.substitutions]
'~/work/bitbucket/maxeda' = 'maxeda'

[directory]
read_only = " ï ½"
style = "bold #c678dd" #purple

[docker_context]
symbol = "ïŒˆ "

[git_branch]
symbol = "îœ¥ "
style = "bold #98c379"  #green

[git_status]
format = '([$up_to_date$ahead_behind]($style) )'
style = "cyan"
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
cherry_pick = '[ğŸ’ PICKING](bold red)'

[nodejs]
symbol = "ï¢˜ "
style = "bold #e5c07b" #yellow

[package]
style = "bold #e06c75" #red

[ruby]
symbol = "îˆ¾ "
style = "bold #e06c75" #red
