# palette = "catppuccin_frappe"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$dart\
$lua\
$nodejs\
$ruby\
$rust\
$line_break\
$character"""

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[[♥](green) ❯](maroon)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory]
# style = "blue"
style = "bold lavender"

# [palettes.catppuccin_frappe]
# rosewater = "#f2d5cf"
# flamingo = "#eebebe"
# pink = "#f4b8e4"
# mauve = "#ca9ee6"
# red = "#e78284"
# maroon = "#ea999c"
# peach = "#ef9f76"
# yellow = "#e5c890"
# green = "#a6d189"
# teal = "#81c8be"
# sky = "#99d1db"
# sapphire = "#85c1dc"
# blue = "#8caaee"
# lavender = "#babbf1"
# text = "#c6d0f5"
# subtext1 = "#b5bfe2"
# subtext0 = "#a5adce"
# overlay2 = "#949cbb"
# overlay1 = "#838ba7"
# overlay0 = "#737994"
# surface2 = "#626880"
# surface1 = "#51576d"
# surface0 = "#414559"
# base = "#303446"
# mantle = "#292c3c"
# crust = "#232634"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
